## **NumPy Library:**

#### **NumPy_Indexing:-** 

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,12)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
arr[8]

np.int64(8)

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11])

In [12]:
slice_of_arr = arr[0:6]

In [13]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
slice_of_arr[:] =77

In [15]:
slice_of_arr

array([77, 77, 77, 77, 77, 77])

In [16]:
arr

array([77, 77, 77, 77, 77, 77,  6,  7,  8,  9, 10, 11])