NumPy Array

In [1]:
my_list = [1,3,4]

In [2]:
import numpy as np

In [3]:
my_newlist = [[1,3,4],[5,6,7],[12,15,16]]

In [4]:
np.array(my_newlist)

array([[ 1,  3,  4],
       [ 5,  6,  7],
       [12, 15, 16]])

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.linspace(0,3,10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.rand(5)

array([0.62889776, 0.45770933, 0.47638155, 0.96017348, 0.28636821])

In [13]:
np.random.rand(5,5)

array([[0.5517618 , 0.69878984, 0.25766145, 0.45690737, 0.57660424],
       [0.3898689 , 0.96778987, 0.47648464, 0.66548908, 0.32394625],
       [0.12986218, 0.59556966, 0.34740699, 0.03132699, 0.68019077],
       [0.06071356, 0.06357556, 0.62870219, 0.55405472, 0.45493738],
       [0.20918858, 0.23461301, 0.66808148, 0.09330809, 0.41662151]])

In [31]:
np.random.randn(3,3)

array([[-0.62523838, -0.26794496,  0.6786926 ],
       [ 0.43584346, -1.37228438, -0.76440182],
       [-0.78496211,  0.67717777, -1.84900016]])

In [32]:
np.random.randn(3)

array([ 0.14308308, -0.14542174,  1.19566113])

In [34]:
np.random.randint(1,88)

82

In [14]:
np.random.randint(1,56,8)

array([42, 18, 35, 29, 26, 41, 11, 38], dtype=int32)

In [20]:
arr = np.arange(25)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
arr.max()

np.int64(24)

In [41]:
ranarr = np.random.randint(0,50,10)

In [42]:
ranarr

array([ 8, 22, 31, 25, 35, 21, 12,  5, 29, 21], dtype=int32)

In [43]:
ranarr.max()

np.int32(35)

In [44]:
ranarr.min()

np.int32(5)

In [45]:
ranarr.argmax()

np.int64(4)

In [46]:
ranarr.argmin()

np.int64(7)

In [47]:
arr.shape

(25,)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
arr = arr.reshape(5,5)

In [50]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
arr.shape

(5, 5)

In [52]:
arr.dtype

dtype('int64')

In [53]:
ranarr.dtype

dtype('int32')