### **NumPy 2D Array Indexing**

In [3]:
import numpy as np

In [6]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [8]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [9]:
arr_2d[0]

array([ 5, 10, 15])

In [10]:
arr_2d[0][0]

np.int64(5)

In [11]:
arr_2d[1][1]

np.int64(25)

In [12]:
arr_2d[2][1]

np.int64(40)

In [13]:
arr_2d[2,1]

np.int64(40)

In [14]:
arr_2d[1,2]

np.int64(30)

In [16]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [17]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [18]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [21]:
arr = np.arange(1,11)

In [22]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
bool_arr = arr > 5

In [26]:
bool_arr 

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [27]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [28]:
arr[arr>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [29]:
arr_2d = np.arange(50).reshape(5,10)

In [30]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [31]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [32]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])