In [1]:
import numpy as np

In [2]:
arr = np.arange(1,11)

In [3]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
arr*arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [7]:
arr+100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [8]:
arr-50

array([-49, -48, -47, -46, -45, -44, -43, -42, -41, -40])

In [9]:
arr**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [10]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [11]:
np.max(arr)

np.int64(10)

In [12]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [13]:
np.log(arr)


array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])